repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-yaml
    args: ["--unsafe"]
  - id: debug-statements
  - id: end-of-file-fixer
    exclude: ".*fits"
  - id: trailing-whitespace
    exclude: ".*fits"

- repo: https://github.com/asottile/pyupgrade
  rev: v2.34.0
  hooks:
    - id: pyupgrade
      args: ["--py38-plus"]
      exclude: "asdf/extern/.*|docs/.*"

- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
    - id: isort

- repo: https://github.com/psf/black
  rev: 22.6.0
  hooks:
    - id: black

- repo: https://github.com/PyCQA/flake8
  rev: 4.0.1
  hooks:
    - id: flake8
      args: ['--ignore=E501']
      exclude: "asdf/extern/.*|docs/.*"

- repo: https://github.com/PyCQA/bandit
  rev: 1.7.4
  hooks:
    - id: bandit
      args: ["-c", "bandit.yaml"]
