name: test

on:
  push:
    paths:
      - '**/*.ipynb'
      - '**/*.yml'
      - '**/*.yaml'
      - '**/*.py'
  pull_request:
    paths:
      - '**/*.ipynb'
      - '**/*.yml'
      - '**/*.yaml'
      - '**/*.py'

defaults:
  run:
    shell: bash -l {0}

jobs:
  verify_install:
    name: verify installed packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          path: |
            ~/conda_pkgs_dir
            /usr/share/miniconda/envs/test
          key:
            conda-${{ runner.os }}-${{ hashFiles('00_install/environment.yml') }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: 00_install/environment.yml
          use-only-tar-bz2: true
      - run: python ./00_install/verify_install.py
  run_notebooks:
    name: run notebooks
    needs: [ verify_install ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          path: |
            ~/conda_pkgs_dir
            /usr/share/miniconda/envs/test
          key:
            conda-${{ runner.os }}-${{ hashFiles('00_install/environment.yml') }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: 00_install/environment.yml
          use-only-tar-bz2: true
      - run: pip install nbcollection
      - run: python -m nbcollection execute .
